language: python
env:
  - TEST_MODE=run_tests
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install: .travis/install.sh
script: .travis/test.sh
after_success: .travis/finish.sh
matrix:
  include:
    - python: "2.7"
      env: TEST_MODE=check_style
    - python: "2.7"
      env: TEST_MODE=measure_coverage
